### ISSUE TITLE
Paper or Preprint?

### ISSUE THREAD

**Issue by starmpcc** [ncbi-nlp/MedCalc-Bench#1]
Hello.

The concept of the dataset seems great.
Is there any paper or preprint that explain this dataset?

Thank you!

**Comment by drqiaojin** [comment]
> Hello.
> 
> The concept of the dataset seems great. Is there any paper or preprint that explain this dataset?
> 
> Thank you!

Thank you for your interest in our work. The preprint is available at https://arxiv.org/abs/2406.12036. We will also add it to the README.

Qiao

**Comment by starmpcc** [comment]
Sounds great, thank you!
