### ISSUE TITLE
Missing files & undefined variables

### ISSUE THREAD

**Issue by starmpcc** [ncbi-nlp/MedCalc-Bench#2]
Hello,

I am currently trying to reproduce the results using the provided codes. However, I encountered some issues:

1. Some template files (e.g., `./templates/pmc_llama.jinja`) are missing.
2. Some variables do not exist. For example, does [this](https://github.com/ncbi-nlp/MedCalc-Bench/blob/18d5b5a10bc5dcfe63261648d6a1e68426f7d5e4/evaluation/run.py#L57) refer to `extracted_answer`? Additionally, should the return variable name be `answer`?
3. There are type conversion errors. Some columns in huggingface contain int64 variables, which cause errors during [pickling](https://github.com/ncbi-nlp/MedCalc-Bench/blob/18d5b5a10bc5dcfe63261648d6a1e68426f7d5e4/evaluation/run.py#L241) or [comparison](https://github.com/ncbi-nlp/MedCalc-Bench/blob/18d5b5a10bc5dcfe63261648d6a1e68426f7d5e4/evaluation/evaluate.py#L10).
4. Does the file `evaluation/one_shot_finalized_explanation.json` is appropriate for `--one_shot_example_path`?

Thank you!

Best regards,
Junu

**Comment by nikhilk7153** [comment]
Hello, I apologize for these issues, but believe that I have resolved all of them in the current main branch. I have run our code for all of the settings (direct answer, zero shot, one shot, and code augmented (for GPT-3.5/4)) and have verified that you can reproduce our results. I have also re-uploaded the dataset on HuggingFace.  For inference in run.py, you only need to add --model and --prompt arguments and so you don't need to worry about the other arguments. Would it be possible for you to try again? Thanks!

**Comment by starmpcc** [comment]
Thank you! It seems to work perfectly.
I've tested Mixtral with the `zero_shot` setting and got an accuracy of 22.0%.
One remaining question is, how was the standard deviation calculated in Table 2?
Aren't the `zero_shot` experiments deterministic?

**Comment by nikhilk7153** [comment]
Hello, 

Yes, the output of the LLMs are deterministic. The standard deviation is calculated as sqrt(accuracy * (1- accuracy)/(total number of instances)) and is meant to show the degree of spread among the instances from the average for a given category.
